<footer class="wrap-footer footer-2 colophon wigetized">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-6 item-footer-four">
				<div class="widget widget_about"> 
					<div class="noo_about_widget">
						<a href="#">
							<img src="assets/images/logo.png" alt="" />
						</a>
						<p>
							<?= $setting->description; ?>
						</p>
					</div>
				</div>
				<div class="widget widget_noo_social"> 
					<div class="noo_social">
						<div class="social-all">
							<a href="#" style="color: #3b5999" class="fab fa-facebook-f"></a>
							<a href="#" style="color: #dd4b39" class="fab fa-google-plus-g"></a>
							<a href="#" style="color: #55acee" class="fab fa-twitter"></a>
							<a href="#" style="color: #cd201f" class="fab fa-youtube"></a>
							
						</div>
					</div>
				</div>
				<div class="widget widget_text">
					<div class="textwidget">
						<div class="copyright">
							<?= date('Y'); ?> <?= $setting->site_name; ?><br/>
							Designed with <i class="fa fa-heart-o"></i> by SG.
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 item-footer-four">
				<div class="widget widget_text">
					<h4 class="widget-title">Contact</h4> 
					<div class="textwidget">
						<h5>Address</h5>
						<p><?= $setting->address; ?></p>
						<h5>Hotline</h5>
						<p>
							<a href="#"><?= $setting->phone1; ?></a><br/>
							<a href="#"><?= $setting->phone2; ?></a>
						</p>
						<h5>Email</h5>
						<p>
							<a href="mailto:contact@organicistore.com">
								<?= $setting->email; ?>
							</a>
						</p>
						<h5>Live Chat</h5>
						<i style="color: #00AFF0" class="fab fa-skype"></i> <?= $setting->skype; ?><br/>
						<i style="color: #665CAC" class="fab fa-viber"></i> <?= $setting->viber; ?><br/>
						<i style="color: #25D366" class="fab fa-whatsapp"></i> <?= $setting->whatsapp; ?>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 item-footer-four">
				<div class="widget widget_flickr">
					<h4 class="widget-title">Photo in flickr</h4>
					<div class='flickr-badge-wrapper'></div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 item-footer-four">
				<div class="widget widget_noo_openhours clear">
					<h4 class="widget-title">Working time</h4> 
					<ul class="noo-openhours">
						<li>
							<span>Monday to Friday: </span>
							<span>08:00am - 08:00pm </span>
						</li>
						<li>
							<span>Saturday &amp; Sunday: </span>
							<span>10:00am - 06:00pm </span>
						</li>
					</ul>
				</div>
				<div class="widget widget_noo_happyhours">
					<h4 class="widget-title">Happy Hours</h4> 
					<ul class="noo-happyhours">
						<li>
							<div>Enjoy discount baked goods. </div>
							<div>06:00 am - 08:00 pm daily </div>
						</li>
					</ul>
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</div>
			</div>
		</div>
	</div>
</footer>