<!doctype html>
<html lang="en-US">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
		<link rel="shortcut icon" href="assets/images/favicon.ico"/>
		<title>Home - <?= $setting->site_name; ?></title>

		<link rel='stylesheet' href='assets/css/bootstrap.min.css' type='text/css' media='all' />
		<link rel='stylesheet' href='assets/css/settings.css' type='text/css' media='all'/>
		<link rel='stylesheet' href='assets/css/owl.carousel.css' type='text/css' media='all'/>
		<link rel='stylesheet' href='assets/css/owl.theme.css' type='text/css' media='all'/>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
		<link rel='stylesheet' href='//fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic,400italic,700italic,900italic' type='text/css' media='all'/>
		<link rel='stylesheet' href='//fonts.googleapis.com/css?family=Pacifico:100,300,400,700,900,300italic,400italic,700italic,900italic' type='text/css' media='all'/>
		<link rel='stylesheet' href='//fonts.googleapis.com/css?family=Anonymous+Pro:' type='text/css' media='all'/>
		<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:700" type="text/css" media="all"/>
		<link rel='stylesheet' href='assets/css/style.css' type='text/css' media='all'/>
		<link rel='stylesheet' href='assets/css/custom.css' type='text/css' media='all'/>
		<link rel="stylesheet" href='assets/css/magnific-popup.css' type='text/css' media='all' />
		<link rel="stylesheet" href='assets/css/style-selector.css' type='text/css' media='all' />
		<link id="style-main-color" rel="stylesheet" href="assets/css/colors/blue.css">
		
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
				<![endif]-->
		<style>
			.noo-header.header-5 .navbar {
					min-height: 160px;
					max-height: 160px;
					
			}
			.noo-header.header-5 .menu-position .navbar-nav>li.noo_megamenu>.sub-menu {
					-webkit-transform: translate(0,-19%);
					-ms-transform: translate(0,-19%);
					-o-transform: translate(0,-19%);
					transform: translate(0,-19%);
			}

			.noo-header.header-5 .menu-position .navbar-nav .sub-menu {
				box-shadow: 0px 20px 30px grey;
			}

			.noo-header.header-5 .noo-main-menu .navbar-nav li>a {
					line-height: 50px;
			}
		</style>
	</head>
	<body>
		<div class="noo-spinner">
			<div class="spinner">
				<div class="cube1"></div>
				<div class="cube2"></div>
			</div>
		</div>
		<div class="site">
			<header class="noo-header header-5 header-static">
				<div class="navbar-wrapper">
					<div class="navbar navbar-default">
						<div class="container">
							<div class="menu-position">
								<div class="navbar-header pull-left">
									<div class="noo_menu_canvas">
										<div class="btn-search noo-search">
											<i class="fa fa-search"></i>
										</div>
										<div data-target=".nav-collapse" class="btn-navbar">
											<span></span>
											<span></span>
											<span></span>
										</div>
									</div>
									<a href="./" class="navbar-brand">
										<img class="noo-logo-img noo-logo-normal" src="assets/images/logo_black.png" alt="">
									</a>
								</div>  
								<?php include("partials/index/header_link_nav.php"); ?>
								<?php include("partials/index/menu.php"); ?>
							</div>
						</div>
					</div>
				</div>
				<div class="search-header5">
					<div class="remove-form"></div>
					<div class="container">
						<form class="form-horizontal">
							<label class="note-search">Type and Press Enter to Search</label>
							<input type="search" name="s" class="form-control" value="" placeholder="Search...">
							<input type="submit" value="Search">
						</form> 
					</div>
				</div>
			</header>
			<div class="main">
				<?php include("partials/index/top_slider.php"); ?>
				<?php include("partials/index/sub_slider.php"); ?>
				
				<?php include("partials/index/new_products.php"); ?>
				<?php include("partials/subscribe.php"); ?>
			</div>
			<?php include("partials/footer.phtml"); ?>
		</div>
		<a href="#" class="go-to-top hidden-print"><i class="fa fa-angle-up"></i></a>
        <?php include("partials/index/footer_home_js.phtml"); ?>
	</body>
</html>