

<script type='text/javascript' src='assets/js/jquery.min.js'></script>
<script type='text/javascript' src='assets/js/bootstrap.min.js'></script>
<script type='text/javascript' src='assets/js/jquery-migrate.min.js'></script>
<script type='text/javascript' src='assets/js/modernizr-2.7.1.min.js'></script>
<script type='text/javascript' src='assets/js/bootstrap.min.js'></script>
<script type='text/javascript' src='assets/js/off-cavnass.js'></script>
<script type='text/javascript' src='assets/js/jquery.cookie.js'></script>

<script type='text/javascript' src='assets/js/script.js'></script>
<script type='text/javascript' src='assets/js/custom.js'></script>
<script type='text/javascript' src='assets/js/imagesloaded.pkgd.min.js'></script>
<script type='text/javascript' src='assets/js/isotope.pkgd.min.js'></script>
<script type='text/javascript' src='assets/js/portfolio.js'></script>
<script type='text/javascript' src='assets/js/jquery.touchSwipe.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.carouFredSel-6.2.1.js'></script>
<script type='text/javascript' src='assets/js/jquery.isotope.min.js'></script>
<script type='text/javascript' src='assets/js/owl.carousel.min.js'></script>
<script type='text/javascript' src='assets/js/jflickrfeed.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.magnific-popup.js'></script>